CREATE TABLE IF NOT EXISTS pub_attempts (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  enterprise_id BIGINT UNSIGNED NOT NULL,
  publish_task_id BIGINT UNSIGNED NOT NULL,
  attempt_number INT UNSIGNED NOT NULL,
  worker_node_id BIGINT UNSIGNED NOT NULL,
  lease_id BIGINT UNSIGNED NOT NULL,
  idempotency_key VARCHAR(128) NOT NULL,
  status VARCHAR(32) NOT NULL,
  started_at DATETIME(6) NOT NULL,
  finished_at DATETIME(6),
  duration_ms BIGINT UNSIGNED NOT NULL DEFAULT 0,
  result_json JSON,
  evidence_json JSON,
  error_category VARCHAR(64),
  error_code VARCHAR(64),
  error_message TEXT,
  client_version VARCHAR(64),
  created_at DATETIME(6) NOT NULL,
  PRIMARY KEY(id),
  UNIQUE KEY uk_pub_attempt_idempotency(enterprise_id, idempotency_key),
  KEY idx_pub_attempt_task(enterprise_id, publish_task_id, attempt_number),
  KEY idx_pub_attempt_lease(lease_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
