CREATE TABLE IF NOT EXISTS ent_realname_authentications (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  enterprise_id BIGINT UNSIGNED NOT NULL,
  type VARCHAR(32) NOT NULL,
  status VARCHAR(32) NOT NULL,
  real_name VARCHAR(128) NOT NULL,
  id_card_number VARCHAR(64) NOT NULL,
  mobile VARCHAR(32) NOT NULL,
  company_name VARCHAR(255),
  registration_no VARCHAR(128),
  license_image_url VARCHAR(1024),
  id_card_image_url VARCHAR(1024),
  reject_reason VARCHAR(512),
  reviewed_by BIGINT UNSIGNED,
  reviewed_at DATETIME(6),
  submitted_at DATETIME(6) NOT NULL,
  created_at DATETIME(6) NOT NULL,
  updated_at DATETIME(6) NOT NULL,
  deleted_at DATETIME(6),
  PRIMARY KEY(id),
  KEY idx_ent_realname_enterprise(enterprise_id),
  KEY idx_ent_realname_status(status),
  KEY idx_ent_realname_type(type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
