CREATE TABLE IF NOT EXISTS cnt_article_generation_tasks (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  enterprise_id BIGINT UNSIGNED NOT NULL,
  article_id BIGINT UNSIGNED,
  article_type_version_id BIGINT UNSIGNED NOT NULL,
  prompt_version_id BIGINT UNSIGNED NOT NULL,
  writing_model_id BIGINT UNSIGNED NOT NULL,
  writing_model_version BIGINT UNSIGNED NOT NULL,
  client_request_id VARCHAR(128) NOT NULL,
  status VARCHAR(32) NOT NULL,
  input_json JSON NOT NULL,
  prompt_snapshot LONGTEXT NOT NULL,
  model_snapshot_json JSON NOT NULL,
  knowledge_refs_json JSON,
  output_json JSON,
  input_tokens BIGINT UNSIGNED NOT NULL DEFAULT 0,
  output_tokens BIGINT UNSIGNED NOT NULL DEFAULT 0,
  cost_micros BIGINT NOT NULL DEFAULT 0,
  error_code VARCHAR(64),
  error_message TEXT,
  attempt_count INT UNSIGNED NOT NULL DEFAULT 0,
  result_article_version_id BIGINT UNSIGNED,
  result_snapshot_id BIGINT UNSIGNED,
  started_at DATETIME(6),
  completed_at DATETIME(6),
  created_at DATETIME(6) NOT NULL,
  updated_at DATETIME(6) NOT NULL,
  deleted_at DATETIME(6),
  PRIMARY KEY (id),
  UNIQUE KEY uk_cnt_generation_request (enterprise_id, client_request_id),
  KEY idx_cnt_generation_tenant_status (enterprise_id, status, created_at),
  KEY idx_cnt_generation_article (enterprise_id, article_id, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
