CREATE TABLE IF NOT EXISTS ops_export_jobs (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  enterprise_id BIGINT UNSIGNED,
  requested_by_type VARCHAR(32) NOT NULL,
  requested_by_id BIGINT UNSIGNED NOT NULL,
  resource_type VARCHAR(64) NOT NULL,
  format VARCHAR(16) NOT NULL,
  filter_json JSON NOT NULL,
  client_request_id VARCHAR(128) NOT NULL,
  status VARCHAR(32) NOT NULL,
  object_key VARCHAR(1024),
  file_hash CHAR(64),
  expires_at DATETIME(6),
  error_message TEXT,
  completed_at DATETIME(6),
  cancelled_at DATETIME(6),
  created_at DATETIME(6) NOT NULL,
  updated_at DATETIME(6) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_ops_export_request (enterprise_id, client_request_id),
  KEY idx_ops_export_inbox (enterprise_id, requested_by_type, requested_by_id, created_at),
  KEY idx_ops_export_execution (status, created_at),
  KEY idx_ops_export_expiry (expires_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
