// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v3"
	"kratos-svr/app/user/internal/biz"
	"kratos-svr/app/user/internal/conf"
	"kratos-svr/app/user/internal/data"
	"kratos-svr/app/user/internal/server"
	"kratos-svr/app/user/internal/service"
	"log/slog"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, auth *conf.Auth, storage *conf.Storage, logger *slog.Logger) (*kratos.App, func(), error) {
	manager, err := newAuthManager(auth)
	if err != nil {
		return nil, nil, err
	}
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	authRepo := data.NewAuthRepo(dataData)
	authUsecase := biz.NewAuthUsecase(authRepo, manager)
	authService := service.NewAuthService(authUsecase)
	brandRepo := data.NewBrandRepo(dataData)
	brandUsecase := biz.NewBrandUsecase(brandRepo)
	brandService := service.NewBrandService(brandUsecase)
	knowledgeRepo := data.NewKnowledgeRepo(dataData)
	knowledgeUsecase := biz.NewKnowledgeUsecase(knowledgeRepo)
	knowledgeService := service.NewKnowledgeService(knowledgeUsecase)
	fileStorage, err := data.NewFileStorage(storage)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	galleryRepo := data.NewGalleryRepo(dataData, fileStorage)
	galleryUsecase := biz.NewGalleryUsecase(galleryRepo)
	galleryService := service.NewGalleryService(galleryUsecase)
	keywordRepo := data.NewKeywordRepo(dataData)
	keywordUsecase := biz.NewKeywordUsecase(keywordRepo)
	keywordDistillationRepo := data.NewKeywordDistillationRepo(dataData)
	keywordQuestionDistiller := data.NewEinoKeywordQuestionDistiller(dataData)
	keywordDistillationUsecase := biz.NewKeywordDistillationUsecase(keywordDistillationRepo, keywordQuestionDistiller)
	keywordService := service.NewKeywordService(keywordUsecase, keywordDistillationUsecase)
	questionRepo := data.NewQuestionRepo(dataData)
	questionUsecase := biz.NewQuestionUsecase(questionRepo)
	questionService := service.NewQuestionService(questionUsecase)
	catalogRepo := data.NewCatalogRepo(dataData)
	catalogUsecase := biz.NewCatalogUsecase(catalogRepo)
	catalogService := service.NewCatalogService(catalogUsecase)
	articleRepo := data.NewArticleRepo(dataData, fileStorage)
	articleUsecase := biz.NewArticleUsecase(articleRepo)
	articleService := service.NewArticleService(articleUsecase)
	articleGenerationRepo := data.NewArticleGenerationRepo(dataData, fileStorage)
	articleGenerator := data.NewEinoArticleGenerator(dataData)
	articleGenerationUsecase := biz.NewArticleGenerationUsecase(articleGenerationRepo, articleGenerator)
	articleGenerationService := service.NewArticleGenerationService(articleGenerationUsecase)
	platformAccountRepo := data.NewPlatformAccountRepo(dataData)
	platformAccountUsecase := biz.NewPlatformAccountUsecase(platformAccountRepo)
	platformAccountService := service.NewPlatformAccountService(platformAccountUsecase)
	clientAuthorizationService := service.NewClientAuthorizationService(platformAccountUsecase, catalogUsecase)
	publishTaskRepo := data.NewPublishTaskRepo(dataData)
	publishTaskUsecase := biz.NewPublishTaskUsecase(publishTaskRepo)
	publishTaskService := service.NewPublishTaskService(publishTaskUsecase)
	geoMonitorRepo := data.NewGeoMonitorRepo(dataData)
	geoMonitorUsecase := biz.NewGeoMonitorUsecase(geoMonitorRepo)
	geoMonitorService := service.NewGeoMonitorService(geoMonitorUsecase)
	geoReportService := service.NewGeoReportService(geoMonitorUsecase)
	notificationRepo := data.NewNotificationRepo(dataData)
	notificationUsecase := biz.NewNotificationUsecase(notificationRepo)
	notificationService := service.NewNotificationService(notificationUsecase)
	exportJobRepo := data.NewExportJobRepo(dataData)
	exportJobUsecase := biz.NewExportJobUsecase(exportJobRepo)
	exportJobService := service.NewExportJobService(exportJobUsecase)
	purchasablePlanRepo := data.NewPurchasablePlanRepo(dataData)
	userSubscriptionOrderRepo := data.NewUserSubscriptionOrderRepo(dataData)
	subscriptionOrderUsecase := biz.NewSubscriptionOrderUsecase(purchasablePlanRepo, userSubscriptionOrderRepo)
	subscriptionOrderService := service.NewSubscriptionOrderService(subscriptionOrderUsecase)
	grpcServer := server.NewGRPCServer(confServer, manager, authService, brandService, knowledgeService, galleryService, keywordService, questionService, catalogService, articleService, articleGenerationService, platformAccountService, clientAuthorizationService, publishTaskService, geoMonitorService, geoReportService, notificationService, exportJobService, subscriptionOrderService)
	geoBrandBoardRepo := data.NewGeoBrandBoardRepo(dataData)
	geoBrandBoardUsecase := biz.NewGeoBrandBoardUsecase(geoBrandBoardRepo)
	geoBrandBoardService := service.NewGeoBrandBoardService(geoBrandBoardUsecase)
	realnameRepo := data.NewRealnameRepo(dataData)
	realnameUsecase := biz.NewRealnameUsecase(realnameRepo)
	realnameService := service.NewRealnameService(realnameUsecase, fileStorage)
	httpServer := server.NewHTTPServer(confServer, manager, authService, brandService, knowledgeService, galleryService, keywordService, questionService, catalogService, articleService, articleGenerationService, platformAccountService, clientAuthorizationService, publishTaskService, geoMonitorService, geoReportService, geoBrandBoardService, notificationService, exportJobService, subscriptionOrderService, realnameService, fileStorage, dataData)
	geoScheduler := biz.NewGeoScheduler(geoMonitorRepo, logger)
	opinionScheduler := biz.NewOpinionScheduler(geoBrandBoardRepo, logger)
	app := newApp(logger, grpcServer, httpServer, geoScheduler, opinionScheduler)
	return app, func() {
		cleanup()
	}, nil
}
