// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v3"
	"kratos-svr/app/admin/internal/biz"
	"kratos-svr/app/admin/internal/conf"
	"kratos-svr/app/admin/internal/data"
	"kratos-svr/app/admin/internal/server"
	"kratos-svr/app/admin/internal/service"
	"log/slog"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, auth *conf.Auth, logger *slog.Logger) (*kratos.App, func(), error) {
	manager, err := newAuthManager(auth)
	if err != nil {
		return nil, nil, err
	}
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	adminAuthorizationRepo := data.NewAdminAuthorizationRepo(dataData)
	adminAuthorizationUsecase := biz.NewAdminAuthorizationUsecase(adminAuthorizationRepo)
	adminAuthRepo := data.NewAdminAuthRepo(dataData)
	adminAuthUsecase := biz.NewAdminAuthUsecase(adminAuthRepo, manager)
	adminAuthService := service.NewAdminAuthService(adminAuthUsecase)
	salesOpportunityRepo := data.NewSalesOpportunityRepo(dataData)
	salesOpportunityUsecase := biz.NewSalesOpportunityUsecase(salesOpportunityRepo)
	salesOpportunityService := service.NewSalesOpportunityService(salesOpportunityUsecase, adminAuthorizationUsecase)
	salesDiagnosisRepo := data.NewSalesDiagnosisRepo(dataData)
	salesDiagnosisRunner := data.NewEinoSalesDiagnosisRunner(dataData)
	salesDiagnosisUsecase := biz.NewSalesDiagnosisUsecase(salesDiagnosisRepo, salesDiagnosisRunner)
	salesDiagnosisService := service.NewSalesDiagnosisService(salesDiagnosisUsecase, adminAuthorizationUsecase)
	enterpriseRepo := data.NewEnterpriseRepo(dataData)
	enterpriseUsecase := biz.NewEnterpriseUsecase(enterpriseRepo)
	enterpriseService := service.NewEnterpriseService(enterpriseUsecase)
	planRepo := data.NewPlanRepo(dataData)
	planUsecase := biz.NewPlanUsecase(planRepo)
	planService := service.NewPlanService(planUsecase)
	adminArticleRepo := data.NewAdminArticleRepo(dataData)
	adminArticleUsecase := biz.NewAdminArticleUsecase(adminArticleRepo)
	articleService := service.NewArticleService(adminArticleUsecase)
	adminPublishTaskRepo := data.NewAdminPublishTaskRepo(dataData)
	adminPublishTaskUsecase := biz.NewAdminPublishTaskUsecase(adminPublishTaskRepo)
	publishTaskService := service.NewPublishTaskService(adminPublishTaskUsecase)
	adminGeoTaskRepo := data.NewAdminGeoTaskRepo(dataData)
	adminGeoTaskUsecase := biz.NewAdminGeoTaskUsecase(adminGeoTaskRepo)
	geoTaskService := service.NewGeoTaskService(adminGeoTaskUsecase)
	workerAdminRepo := data.NewWorkerAdminRepo(dataData)
	workerAdminUsecase := biz.NewWorkerAdminUsecase(workerAdminRepo)
	workerTaskRepo := data.NewWorkerTaskRepo(dataData)
	workerTaskUsecase := biz.NewWorkerTaskUsecase(workerTaskRepo)
	workerService := service.NewWorkerService(workerAdminUsecase, workerTaskUsecase)
	workerExecutionService := service.NewWorkerExecutionService(workerTaskUsecase)
	adminAuditLogRepo := data.NewAdminAuditLogRepo(dataData)
	adminAuditLogUsecase := biz.NewAdminAuditLogUsecase(adminAuditLogRepo)
	auditLogService := service.NewAuditLogService(adminAuditLogUsecase)
	systemSettingRepo := data.NewSystemSettingRepo(dataData)
	systemSettingUsecase := biz.NewSystemSettingUsecase(systemSettingRepo)
	systemSettingService := service.NewSystemSettingService(systemSettingUsecase)
	dashboardRepo := data.NewDashboardRepo(dataData)
	dashboardUsecase := biz.NewDashboardUsecase(dashboardRepo)
	dashboardService := service.NewDashboardService(dashboardUsecase)
	adminAlertRepo := data.NewAdminAlertRepo(dataData)
	adminAlertUsecase := biz.NewAdminAlertUsecase(adminAlertRepo)
	alertService := service.NewAlertService(adminAlertUsecase)
	adminRoleRepo := data.NewAdminRoleRepo(dataData)
	adminRoleUsecase := biz.NewAdminRoleUsecase(adminRoleRepo)
	adminRoleService := service.NewAdminRoleService(adminRoleUsecase)
	adminUserRepo := data.NewAdminUserRepo(dataData)
	adminUserUsecase := biz.NewAdminUserUsecase(adminUserRepo)
	adminUserService := service.NewAdminUserService(adminUserUsecase)
	articleTypeRepo := data.NewArticleTypeRepo(dataData)
	articleTypeUsecase := biz.NewArticleTypeUsecase(articleTypeRepo)
	articleTypeService := service.NewArticleTypeService(articleTypeUsecase)
	writingModelRepo := data.NewWritingModelRepo(dataData)
	writingModelUsecase := biz.NewWritingModelUsecase(writingModelRepo)
	writingModelService := service.NewWritingModelService(writingModelUsecase)
	publishChannelRepo := data.NewPublishChannelRepo(dataData)
	publishChannelUsecase := biz.NewPublishChannelUsecase(publishChannelRepo)
	iconStorage, err := service.NewIconStorage(confServer)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	publishChannelService := service.NewPublishChannelService(publishChannelUsecase, iconStorage)
	customerAuthorizationRepo := data.NewCustomerAuthorizationRepo(dataData)
	customerAuthorizationUsecase := biz.NewCustomerAuthorizationUsecase(customerAuthorizationRepo)
	customerAuthorizationService := service.NewCustomerAuthorizationService(customerAuthorizationUsecase)
	inclusionSiteRepo := data.NewInclusionSiteRepo(dataData)
	inclusionSiteUsecase := biz.NewInclusionSiteUsecase(inclusionSiteRepo)
	inclusionSiteService := service.NewInclusionSiteService(inclusionSiteUsecase, iconStorage)
	subscriptionOrderRepo := data.NewSubscriptionOrderRepo(dataData)
	billingTxRepo := data.NewBillingTxRepo(dataData)
	subscriptionOrderUsecase := biz.NewSubscriptionOrderUsecase(subscriptionOrderRepo, planRepo, billingTxRepo)
	subscriptionOrderService := service.NewSubscriptionOrderService(subscriptionOrderUsecase, planUsecase, enterpriseUsecase)
	billingConfigUsecase := biz.NewBillingConfigUsecase(systemSettingRepo)
	billingConfigService := service.NewBillingConfigService(billingConfigUsecase)
	grpcServer := server.NewGRPCServer(confServer, manager, adminAuthorizationUsecase, adminAuthService, salesOpportunityService, salesDiagnosisService, enterpriseService, planService, articleService, publishTaskService, geoTaskService, workerService, workerExecutionService, auditLogService, systemSettingService, dashboardService, alertService, adminRoleService, adminUserService, articleTypeService, writingModelService, publishChannelService, customerAuthorizationService, inclusionSiteService, subscriptionOrderService, billingConfigService)
	realnameRepo := data.NewRealnameRepo(dataData)
	realnameUsecase := biz.NewRealnameUsecase(realnameRepo)
	realnameAuthenticationService := service.NewRealnameAuthenticationService(realnameUsecase)
	httpServer := server.NewHTTPServer(confServer, manager, adminAuthorizationUsecase, adminAuthService, salesOpportunityService, salesDiagnosisService, enterpriseService, planService, articleService, publishTaskService, geoTaskService, workerService, workerExecutionService, auditLogService, systemSettingService, dashboardService, alertService, adminRoleService, adminUserService, articleTypeService, writingModelService, publishChannelService, customerAuthorizationService, inclusionSiteService, subscriptionOrderService, billingConfigService, realnameAuthenticationService, iconStorage)
	salesDiagnosisWorker := server.NewSalesDiagnosisWorker(confData, salesDiagnosisUsecase, logger)
	billingSchedulerRepo := data.NewBillingSchedulerRepo(dataData)
	billingScheduler := biz.NewBillingScheduler(billingSchedulerRepo, logger)
	app := newApp(logger, grpcServer, httpServer, salesDiagnosisWorker, billingScheduler)
	return app, func() {
		cleanup()
	}, nil
}
